[build]
    command = "bower install"

[[redirects]]
    from = "/store.json"
    to = "https://cloud-emoticon-store-bridge.herokuapp.com/json"
    status = 200

[[redirects]]
    from = "/store"
    to = "https://cloud-emoticon-store-bridge.herokuapp.com"
    status = 200

[[redirects]]
    from = "/2"
    to = "https://cloudemoticon2-alpha.netlify.app"
    status = 301
